### ISSUE TITLE
Form checkmark icon not converted

### ISSUE THREAD

**Issue by froston** [dichovsky/pdf-to-png-converter#18]
When a PDF form with checkboxes checked is converted to an image, those checkmarks icons are missing.
I tried to combine `disableFontFace` and `useSystemFonts` options but without success. Any solution to this? Thanks!

**Comment by dichovsky** [comment]
> When a PDF form with checkboxes checked is converted to an image, those checkmarks icons are missing. I tried to combine `disableFontFace` and `useSystemFonts` options but without success. Any solution to this? Thanks!

Could you share such file with me?

**Comment by froston** [comment]
Sorry but I can't share the file itself for property reasons, however I can share some more details. Seem to be related to a missing standard font _FoxitDingbats_.

This is how the character looks like in the PDF:
![image](https://user-images.githubusercontent.com/24678624/179424573-5c8ea7c2-fc09-427c-ac8e-60d6d4d70cab.png)

Log:
`Warning: fetchStandardFontData: failed to fetch file "FoxitDingbats.pfb" with "UnknownErrorException: The standard font "baseUrl" parameter must be specified, ensure that the "standardFontDataUrl" API parameter is provided.".`

Whe I tried to set standardFontDataUrl following messages:
`Warning: fetchStandardFontData: failed to fetch file "foxitDingbats.pfb" with "UnknownErrorException: Unable to load font data at https://unpkg.com/pdfjs-dist@2.14.305/standard_fonts/.`

`Warning: fetchStandardFontData: failed to fetch file "foxitDingbats.pfb" with "UnknownErrorException: Unable to load font data at ../node_modules/pdfjs-dist/standard_fonts/.`

**Comment by dichovsky** [comment]
Please try v3.3.0
