### ISSUE TITLE
Fallback fonts

### ISSUE THREAD

**Issue by jakubmirejovsky** [dichovsky/pdf-to-png-converter#28]
Hi, is there any correct way to tell the converter to fallback fonts if the glyphs can't be rendered - per glyph?
Related issues:
- https://github.com/mozilla/pdf.js/issues/11860
- https://github.com/mozilla/pdf.js/issues/11311

Example of file which renders poorly: https://drive.google.com/file/d/1Z-cF3Vba1rbFCM6Qj5iDttqs9aquYGJi/view?usp=share_link

I tried disableFontFace true, false, useSystemFonts both true and false. No combination returned a correct render.

Any help will be appriciated! :)

**Comment by troyqa** [comment]
Hi there, @jakubmirejovsky, I have exactly the same problem, did you found solution for this?

**Comment by lbhmygod** [comment]
Hi, hope my experience can help you.

I use this package to convert pdf, but recently I found some pdf texts are missing after conversion. So I tried to debug this, and set  `verbosityLevel` to 5 to show all logs. And I found this error in log:

> Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Regular.ttf" with "UnknownErrorException: Unable to load font data at: ../node_modules/pdfjs-dist/standard_fonts/LiberationSans-Regular.ttf".

> Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Helvetica_path_T.".

After several hours no-use trying to add missing font, I realized this error is thrown by its dependent pdf.js package, and as they said, they have fixed this issue by adding default font, but we need to reference correctly https://github.com/mozilla/pdf.js/issues/4244#issuecomment-1232548915 

So I change this line [const standardFontDataUrl = '../node_modules/pdfjs-dist/standard_fonts/';](https://github.com/dichovsky/pdf-to-png-converter/blob/3a3376afbb63a78a93fd2440342e939dae7b9ce8/src/props.to.pdf.doc.init.params.ts#L9C5-L9C78) in my local, and it works!  Everything renders correctly! You can either change it to 
`const standardFontDataUrl = './node_modules/pdfjs-dist/standard_fonts/';` 
or 
`const standardFontDataUrl = join(__dirname, '../../../node_modules/pdfjs-dist/standard_fonts/');`

**Comment by fabianobonomini** [comment]
Same problem here. I got a blank white pdf.

**Comment by ngekoding** [comment]
> Hi, hope my experience can help you.
> 
> I use this package to convert pdf, but recently I found some pdf texts are missing after conversion. So I tried to debug this, and set `verbosityLevel` to 5 to show all logs. And I found this error in log:
> 
> > Warning: fetchStandardFontData: failed to fetch file "LiberationSans-Regular.ttf" with "UnknownErrorException: Unable to load font data at: ../node_modules/pdfjs-dist/standard_fonts/LiberationSans-Regular.ttf".
> 
> > Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Helvetica_path_T.".
> 
> After several hours no-use trying to add missing font, I realized this error is thrown by its dependent pdf.js package, and as they said, they have fixed this issue by adding default font, but we need to reference correctly [mozilla/pdf.js#4244 (comment)](https://github.com/mozilla/pdf.js/issues/4244#issuecomment-1232548915)
> 
> So I change this line [const standardFontDataUrl = '../node_modules/pdfjs-dist/standard_fonts/';](https://github.com/dichovsky/pdf-to-png-converter/blob/3a3376afbb63a78a93fd2440342e939dae7b9ce8/src/props.to.pdf.doc.init.params.ts#L9C5-L9C78) in my local, and it works! Everything renders correctly! You can either change it to `const standardFontDataUrl = './node_modules/pdfjs-dist/standard_fonts/';` or `const standardFontDataUrl = join(__dirname, '../../../node_modules/pdfjs-dist/standard_fonts/');`

Works for me! Thank you.

**Comment by dichovsky** [comment]
Please try v3.3.0

**Comment by svrnwnsch** [comment]
There is still a bug if you e.g. run your code inside of docker and have your `WORKDIR` variable set to some other folder. In this case you still get the same error: `Warning: UnknownErrorException: Unable to load font data at: /opt/backend/node_modules/pdfjs-dist/standard_fonts/LiberationSans-Regular.ttf` Because the files are maybe located in `/opt/backend/api/node_modules/pdfjs-dist/standard_fonts/LiberationSans-Regular.ttf

**Comment by dichovsky** [comment]
> I face a very similar issue that the font fallback location is not correctly found. I use pnpm and the sub dependencies are not installed next to pdf-to-png-convert in the node modules folder. My work around was to extend my `package.json` to explicitly list `pdfjs-dist` to have it installed in the node_modules directory where it expected.

pnpm has not been tested and is not supported at this time
