### ISSUE TITLE
Updated canvas version?

### ISSUE THREAD

**Issue by ligius-** [dichovsky/pdf-to-png-converter#29]
Can someone please update the canvas version to 2.11.0? The required one, 2.10.2 is not prebuilt for node18 (ABI v108) but the newer one is. I tried forcing the canvas dependency to the newer one but the plugin stops responding, did not debug why yet.

**Comment by dichovsky** [comment]
> Can someone please update the canvas version to 2.11.0? The required one, 2.10.2 is not prebuilt for node18 (ABI v108) but the newer one is. I tried forcing the canvas dependency to the newer one but the plugin stops responding, did not debug why yet.

Please try v3

**Comment by jalog** [comment]
I have the same problem. node-pre-gyp error in node18.

**Comment by dichovsky** [comment]
Have you tried 3.3.0 ?
