### ISSUE TITLE
For some PDFs an error can cause the process to run out of memory

### ISSUE THREAD

**Issue by Zirafnik** [dichovsky/pdf-to-png-converter#33]
A PDF with many pages, causes the Node to run out of memory.

~~This is a similar issue to the one in 'pdf2pic' library: https://github.com/yakovmeister/pdf2image/issues/54~~

~~It can be solved with manual batching, with arrays of page numbers, but it is not a sexy solution, as you first need to determine the number of pages in the document with an external library (such as 'pdfjs-dist') and then create the arrays, allowing for non-even number of pages.~~

**Comment by Zirafnik** [comment]
Update: The batching doesn't work. 

Event with setting the output folder, the library still saves buffers to memory, which eventually overruns it.

**Comment by AChangXD** [comment]
@Zirafnik Same issue here

**Comment by dichovsky** [comment]
Please try v3.3.0
