### ISSUE TITLE
Library requires system requirements

### ISSUE THREAD

**Issue by jakeleventhal** [dichovsky/pdf-to-png-converter#35]
Similar to #26, I am getting the following error:
```
Error: dlopen(/Users/jakeleventhal/Code/Ecominate/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node, 0x0001): Library not loaded: /opt/homebrew/opt/pango/lib/libpangocairo-1.0.0.dylib
```

I want to use this on a vercel serverless function, but I need system requirements.

**Comment by dichovsky** [comment]
See https://github.com/Automattic/node-canvas/wiki/Installation:-AWS-Lambda with `node-canves` requirements
