### ISSUE TITLE
Add ability to specify viewport size

### ISSUE THREAD

**Issue by jakeleventhal** [dichovsky/pdf-to-png-converter#36]
We should be able to specify a viewport size. A scaling factor isn't sufficient to know how large the final image is

**Comment by dichovsky** [comment]
> We should be able to specify a viewport size. A scaling factor isn't sufficient to know how large the final image is

Hey @jakeleventhal
I suggest using a separate library for this, like [sharp](https://www.npmjs.com/package/sharp)
not to complicate this library
