### ISSUE TITLE
While Deploying my web app in Vercel its saying "The Serverless Function "index.js" is 51.71mb which exceeds the maximum size limit of 50mb."

### ISSUE THREAD

**Issue by awesome-yasin** [dichovsky/pdf-to-png-converter#38]
While Deploying my web app in Vercel its saying "The Serverless Function "index.js" is 51.71mb which exceeds the maximum size limit of 50mb." Please remove files that are large from package

**Comment by AChangXD** [comment]
@awesome-yasin I believe this is caused by pdfjs-dist

**Comment by dichovsky** [comment]
Sorry, I am not able to reproduce this issue
