### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by fabianobonomini** [dichovsky/pdf-to-png-converter#40]
I one of my jest test. using typescript. I got this error

` 
2 | import request from 'supertest';
  3 | import { configureToMatchImageSnapshot } from 'jest-image-snapshot';
  4 | import { PngPageOutput, pdfToPng } from 'pdf-to-png-converter';
     | ^
 5 | import { app, disposeResources, mongoClient } from '../app';
`

any ideas?

**Comment by mtbrum** [comment]
I have the same error

**Comment by MattRiddell** [comment]
Same here

**Comment by Mustafa-Aswadi** [comment]
same error

**Comment by andrewkrippner** [comment]
Same

**Comment by andrewkrippner** [comment]
It appears this occurs on Node 16 but not Node 20.

**Comment by dichovsky** [comment]
node 16 is not supported. minimal version is 18

and also Jest doesn’t natively support ESM yet, so I use vitest instead
