### ISSUE TITLE
Failed to parse this pdf:

### ISSUE THREAD

**Issue by AChangXD** [dichovsky/pdf-to-png-converter#41]
[sample.pdf](https://github.com/dichovsky/pdf-to-png-converter/files/13329315/sample.pdf)

This is a sample pdf that pdf-to-png-converter is failing to parse. It returns blank pngs (all white)

**Comment by Feeloh** [comment]
I also got this issue, with some pdf(s) it renders a blank canvas.

**Comment by AChangXD** [comment]
> I also got this issue, with some pdf(s) it renders a blank canvas.

If you use text retrieval after getDocument, it does show up

**Comment by Feeloh** [comment]
> > I also got this issue, with some pdf(s) it renders a blank canvas.
> 
> If you use text retrieval after getDocument, it does show up

Thanks, the issue is I am dynamically attaching the generated images to an excel file. 
I have resorted to using another package for now.

Thank you very much.

**Comment by AChangXD** [comment]
> package

@Feeloh What package did you end up using? Could you kindly share a link please? :)

**Comment by AChangXD** [comment]
So seems like PDFjs is parsing things properly? https://jsfiddle.net/AChangXD/buno8j9s/1/. So most likely an issue with `canvas`

**Comment by Feeloh** [comment]
@AChangXD I opted for https://www.npmjs.com/package/pdf-to-img 
so far so good, the failed test pdfs are rendering well.

**Comment by AChangXD** [comment]
> > [sample.pdf](https://github.com/dichovsky/pdf-to-png-converter/files/13329315/sample.pdf)
> > This is a sample pdf that pdf-to-png-converter is failing to parse. It returns blank pngs (all white)
> 
> For this particular file use
> 
> ```
>         disableFontFace: false
>         useSystemFonts: false
> ```
> 
> File is rendered in my side

Is there a reason why those parameters aren't the default setting?

**Comment by dichovsky** [comment]
> > > [sample.pdf](https://github.com/dichovsky/pdf-to-png-converter/files/13329315/sample.pdf)
> > > This is a sample pdf that pdf-to-png-converter is failing to parse. It returns blank pngs (all white)
> > 
> > For this particular file use
> > 
> > ```
> >         disableFontFace: false
> >         useSystemFonts: false
> > ```
> > 
> > File is rendered in my side
> 
> Is there a reason why those parameters aren't the default setting?

Different documents require different parameters, there is no golden rule. These params are set to values that I use in other libs for testing on macos
