### ISSUE TITLE
Error: No "GlobalWorkerOptions.workerSrc" specified.

### ISSUE THREAD

**Issue by DanSketic** [dichovsky/pdf-to-png-converter#45]
![Screenshot 2024-05-04 100908](https://github.com/dichovsky/pdf-to-png-converter/assets/23483901/41357a01-fd1a-412d-a44b-5e0558d93e08)

**Comment by dichovsky** [comment]
Please try v3.3.0

**Comment by dichovsky** [comment]
> ![Screenshot 2024-05-04 100908](https://private-user-images.githubusercontent.com/23483901/327934528-41357a01-fd1a-412d-a44b-5e0558d93e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTUyMjEsIm5iZiI6MTczNDIxNDkyMSwicGF0aCI6Ii8yMzQ4MzkwMS8zMjc5MzQ1MjgtNDEzNTdhMDEtZmQxYS00MTJkLWE0NGItNWUwNTU4ZDkzZTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDIyMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYTUzNDBkMzNkYTdhYmFiODZiMTE3MmZhNDdhNTkyNTlhYWVkNWNiNWE0Y2YzODczMjUwMjlkYjVlODQ5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ss6LU1Uo2jQWbQqBQ4U7uVYxdGtlBtCGp5glhZyhHLU)

Currently "node-canvas" replaced with "@napi-rs/canvas". It seems the worker issue was there. Please try v3.6.3

**Comment by DanSketic** [comment]
Thank you for your help!
