### ISSUE TITLE
Update canvas API usage

### ISSUE THREAD

**Issue by Zirafnik** [dichovsky/pdf-to-png-converter#50]
Upon running the function this warning is printed in the terminal:
`Deprecated API usage: `canvasFactory`-instance option, please use `CanvasFactory` instead.`

**Comment by dichovsky** [comment]
> Upon running the function this warning is printed in the terminal: `Deprecated API usage: `canvasFactory`-instance option, please use `CanvasFactory` instead.`

Currently "node-canvas" replaced with "@napi-rs/canvas". Please try v3.6.3
