### ISSUE TITLE
outputFileMask option should override '_page'

### ISSUE THREAD

**Issue by Zirafnik** [dichovsky/pdf-to-png-converter#51]
`outputFileMask` option should overwrite the whole part of the name before '_{num}'. Currently the output equals to:
```js
{
    outputFileMask: 'image',
}

// Output: image_page_1.png
```
What I believe should be more appropriate:
```js
{
    outputFileMask: 'image',
}

// Output: image_1.png
```

The `_page` part of the name is unnecessary and because I cannot override it while creating the images, I have to rename all of them again afterwards (which is obviously less than optimal).

Additionally, perhaps a different name or a more detailed documentation for this option could be added, as the documentation was not at all clear in what happens.

**Comment by dichovsky** [comment]
> `outputFileMask` option should overwrite the whole part of the name before '_{num}'. Currently the output equals to:
> 
> ```js
> {
>     outputFileMask: 'image',
> }
> 
> // Output: image_page_1.png
> ```
> 
> What I believe should be more appropriate:
> 
> ```js
> {
>     outputFileMask: 'image',
> }
> 
> // Output: image_1.png
> ```
> 
> The `_page` part of the name is unnecessary and because I cannot override it while creating the images, I have to rename all of them again afterwards (which is obviously less than optimal).
> 
> Additionally, perhaps a different name or a more detailed documentation for this option could be added, as the documentation was not at all clear in what happens.

Please try v3.6.3
