### ISSUE TITLE
Custom naming function setting

### ISSUE THREAD

**Issue by Zirafnik** [dichovsky/pdf-to-png-converter#54]
I propose another setting to be added for the option of providing a custom naming function. This function would allow you to create custom image names, which completely override the `outputFileMask` (see #51) and the numbering system (see #52).

```js
// Settings object
{
   namingFunction: (num) => {
       // do something and return a custom string
       return `squared_numbers_${Math.sqrt(num)}`;
   }
}

// Output for 2nd image: squared_numbers_4.png

**Comment by dichovsky** [comment]
> I propose another setting to be added for the option of providing a custom naming function. This function would allow you to create custom image names, which completely override the `outputFileMask` (see #51) and the numbering system (see #52).
> 
> ```js
> // Settings object
> {
>    namingFunction: (num) => {
>        // do something and return a custom string
>        return `squared_numbers_${Math.sqrt(num)}`;
>    }
> }
> 
> // Output for 2nd image: squared_numbers_4.png
> ```

Please try v3.6.3
