### ISSUE TITLE
Cannot read properties of undefined (reading 'createCanvas')

### ISSUE THREAD

**Issue by NotVenuMadhav** [dichovsky/pdf-to-png-converter#60]
Im trying to use the package for one of my usecases, but it throws me a TypeError: Cannot read properties of undefined (reading 'createCanvas')

**Comment by rvitaliy** [comment]
@dichovsky i reproduce this error on nodejs 22.11.0
in this PR https://github.com/dichovsky/pdf-visual-compare/pull/10/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R12 i can't add tests for v22 for this error
