### ISSUE TITLE
Char are missing

### ISSUE THREAD

**Issue by ashumsd7** [dichovsky/pdf-to-png-converter#61]
![image](https://github.com/user-attachments/assets/a00a979f-fc9b-4f05-b4a5-226ce9c45de5)

`import  { pdfToPng }  from 'pdf-to-png-converter'
(async () => {
 
  let file = './sample.pdf'
 
  const pngPages = await pdfToPng(file, { // The function accepts PDF file path or a Buffer
    disableFontFace: false, // When `false`, fonts will be rendered using a built-in font renderer that constructs the glyphs with primitive path commands. Default value is true.
    useSystemFonts: false, // When `true`, fonts that aren't embedded in the PDF document will fallback to a system font. Default value is false.
    enableXfa: false, // Render Xfa forms if any. Default value is false.
    viewportScale: 2.0, // The desired scale of PNG viewport. Default value is 1.0.
    outputFolder: 'output/folder', // Folder to write output PNG files. If not specified, PNG output will be available only as a Buffer content, without saving to a file.
    // outputFileMaskFunc, // Output filename mask function.
    pdfFilePassword: 'pa$$word', // Password for encrypted PDF.
    pagesToProcess: [1, 3, 11], // Subset of pages to convert (first page = 1), other pages will be skipped if specified.
    strictPagesToProcess: false, // When `true`, will throw an error if specified page number in pagesToProcess is invalid, otherwise will skip invalid page. Default value is false.
    verbosityLevel: 0 // Verbosity level. ERRORS: 0, WARNINGS: 1, INFOS: 5. Default value is 0.
});
console.log("pngPages",pngPages);
})();`

**Comment by dichovsky** [comment]
> ![image](https://private-user-images.githubusercontent.com/40313523/390520653-a00a979f-fc9b-4f05-b4a5-226ce9c45de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMTQzOTksIm5iZiI6MTczNDIxNDA5OSwicGF0aCI6Ii80MDMxMzUyMy8zOTA1MjA2NTMtYTAwYTk3OWYtZmM5Yi00ZjA1LWI0YTUtMjI2Y2U5YzQ1ZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDIyMDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MTk2ODMzM2QyODdkYmMzMmM5Njg5MDFmZDE5OTI0NGI4MTczYWY4ZWQzMmZiZjAzNzU5ZjZlNDg2NWEzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8xO_MUgGB3CIiCRmxcrPA6PTBHSvFsG4b5Ns5yeepxU)
> 
> `import { pdfToPng } from 'pdf-to-png-converter' (async () => {
> 
> let file = './sample.pdf'
> 
> const pngPages = await pdfToPng(file, { // The function accepts PDF file path or a Buffer disableFontFace: false, // When `false`, fonts will be rendered using a built-in font renderer that constructs the glyphs with primitive path commands. Default value is true. useSystemFonts: false, // When `true`, fonts that aren't embedded in the PDF document will fallback to a system font. Default value is false. enableXfa: false, // Render Xfa forms if any. Default value is false. viewportScale: 2.0, // The desired scale of PNG viewport. Default value is 1.0. outputFolder: 'output/folder', // Folder to write output PNG files. If not specified, PNG output will be available only as a Buffer content, without saving to a file. // outputFileMaskFunc, // Output filename mask function. pdfFilePassword: 'pa$$word', // Password for encrypted PDF. pagesToProcess: [1, 3, 11], // Subset of pages to convert (first page = 1), other pages will be skipped if specified. strictPagesToProcess: false, // When `true`, will throw an error if specified page number in pagesToProcess is invalid, otherwise will skip invalid page. Default value is false. verbosityLevel: 0 // Verbosity level. ERRORS: 0, WARNINGS: 1, INFOS: 5. Default value is 0. }); console.log("pngPages",pngPages); })();`

You have disabled font faces and system fonts, so it is expected that no characters will be visible. Try default configuration.
