### ISSUE TITLE
Error: Failed to convert JavaScript value `Undefined` into rust type `String

### ISSUE THREAD

**Issue by luke-rogers** [dichovsky/pdf-to-png-converter#62]
Not sure how exactly this is happening in my environment but I believe its related to this change to replace `canvas` with `@napi-rs/canvas`.

[Replace the canvas package with @napi-rs/canvas](https://github.com/mozilla/pdf.js/pull/19015/files#top)

```
Error: Failed to convert JavaScript value `Undefined` into rust type `String`
    at /workspace/node_modules/pdf-to-png-converter/out/pdf.to.png.js:58:33
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/node_modules/pdf-to-png-converter/out/pdf.to.png.js:5:58)
```

I'm sure this will need to be fixed when the `pdfjs-dist` dependency is updated in this library.

**Comment by luke-rogers** [comment]
Pinning to version `4.7.76` fixed the issue. This will need to be fixed in this library when upgrading to version `4.9.124` or above of `pdfjs-dist`.

**Comment by NotVenuMadhav** [comment]
> Pinning to version `4.7.76` fixed the issue. This will need to be fixed in this library when upgrading to version `4.9.124` or above of `pdfjs-dist`.

how can i do this? Where do i have to update this change

**Comment by NotVenuMadhav** [comment]
> Pinning to version `4.7.76` fixed the issue. This will need to be fixed in this library when upgrading to version `4.9.124` or above of `pdfjs-dist`.

1) How do i pin it to version `4.7.76`.
Is it in the node_modules? > pdfjs-dist>package.json> version> `4.7.76`.
