### ISSUE TITLE
Error import pdfToPng function. 3.6.0 version

### ISSUE THREAD

**Issue by bloodgang94** [dichovsky/pdf-to-png-converter#65]
Hello! I would like to thank you for the quick solution to the problem for node 22. But the latest version does not import the pdfToPng function correctly. It was probably broken here
https://github.com/dichovsky/pdf-to-png-converter/pull/64/files
![image](https://github.com/user-attachments/assets/d6af7f4c-1ceb-46a3-9a70-15a88efeb20d)

**Comment by dichovsky** [comment]
> Hello! I would like to thank you for the quick solution to the problem for node 22. But the latest version does not import the pdfToPng function correctly. It was probably broken here https://github.com/dichovsky/pdf-to-png-converter/pull/64/files ![image](https://private-user-images.githubusercontent.com/63465285/393619360-d6af7f4c-1ceb-46a3-9a70-15a88efeb20d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2OTc2MjYsIm5iZiI6MTczMzY5NzMyNiwicGF0aCI6Ii82MzQ2NTI4NS8zOTM2MTkzNjAtZDZhZjdmNGMtMWNlYi00NmEzLTlhNzAtMTVhODhlZmViMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDIyMzUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OWMxNWZhNWVlN2MxZWIzNWZjN2E5NDU5MTdmMjQ5ZjIyNTA2YzAxODMwMzMwY2FjZjEwYjg3NWY3MGViNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V10qn3fZwlMIeDMENTkO-yWedRUMWWH1HhN2rqOp730)

Hi @bloodgang94 
Could you provide repro steps ? 
Did you try to clean up node_modules folder?
It works on my side

**Comment by bloodgang94** [comment]
> > Hello! I would like to thank you for the quick solution to the problem for node 22. But the latest version does not import the pdfToPng function correctly. It was probably broken here https://github.com/dichovsky/pdf-to-png-converter/pull/64/files ![image](https://private-user-images.githubusercontent.com/63465285/393619360-d6af7f4c-1ceb-46a3-9a70-15a88efeb20d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2OTc2MjYsIm5iZiI6MTczMzY5NzMyNiwicGF0aCI6Ii82MzQ2NTI4NS8zOTM2MTkzNjAtZDZhZjdmNGMtMWNlYi00NmEzLTlhNzAtMTVhODhlZmViMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDIyMzUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OWMxNWZhNWVlN2MxZWIzNWZjN2E5NDU5MTdmMjQ5ZjIyNTA2YzAxODMwMzMwY2FjZjEwYjg3NWY3MGViNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V10qn3fZwlMIeDMENTkO-yWedRUMWWH1HhN2rqOp730)
> 
> Hi @bloodgang94 Could you provide repro steps ? Did you try to clean up node_modules folder? It works on my side

Yes, of course, [https://github.com/bloodgang94/pdf-to-png-reproduce](https://github.com/bloodgang94/pdf-to-png-reproduce)

**Comment by GreenFlag31** [comment]
![image](https://github.com/user-attachments/assets/a4150958-13e3-4c06-8563-ba9a49345238)

**Comment by NotVenuMadhav** [comment]
Im having the same issue

**Comment by dichovsky** [comment]
> Im having the same issue
> 
> Steps:
> 
> 1. Install the latest version of the package
> 2. run the app
> 
> Tried removing node_modules are installing them again. But it doesnt work

@NotVenuMadhav @bloodgang94 please try v3.6.3

**Comment by bloodgang94** [comment]
@dichovsky , this problem has been resolved. can be closed
