### ISSUE TITLE
Some PNGs are not converted correctly (blank areas)

### ISSUE THREAD

**Issue by elisaliv** [dichovsky/pdf-to-png-converter#7]
Hi, and thank you for your work! 
I am using this library to convert various PDFs to images. It works for most of them, but not for some. 

1. With [this](http://www.africau.edu/images/default/sample.pdf) simple one-page PDF, a completely blank page is returned:
<img width="1010" alt="Screenshot 2022-01-18 at 15 58 37" src="https://user-images.githubusercontent.com/49102376/149962037-82e2b723-14b2-488b-948c-d9fb45bf5d22.png">

2. With [this](https://www.kdp.org/resources/pdf/careercenter/Compiling_a_Curriculum_Vitae.pdf) one, that is a bit more structured, only the footer shows on the PNGs for pages 1--5, whereas page 6 shows correctly:
<img width="1008" alt="Schermata 2022-01-18 alle 16 07 41" src="https://user-images.githubusercontent.com/49102376/149964146-85accbd7-cab3-49e8-9be6-8196ab9ad674.png">

It looks like a text conversion issue -- however, I converted other PDFs that contain text without encountering the issue. For example, [this](https://www.unipg.it/files/pagine/410/4-PDF-A.pdf) one looks good.

Any ideas on what the problem could be?

**Comment by dichovsky** [comment]
Hi Elisa, 
Thank you for the request.

Please try the following:
1 . Try to enable `PdfToPngOptions.disableFontFace`: If disabled, fonts will be rendered using a built-in font renderer that constructs the glyphs with primitive path commands. Default value is `true`
2. Try to disable `PdfToPngOptions.useSystemFonts`: false, // If enabled, fonts that aren't embedded in the PDF document will fallback to a system font. Default value is `false`

Let me know if it works for you

**Comment by elisaliv** [comment]
Hi Igor, thank you for your quick answer.

I have tried with both settings you suggested: by setting `disableFontFace` to `false`, the text is correctly displayed, but the font looks quite ugly:
<img width="1062" alt="Schermata 2022-01-18 alle 17 58 49" src="https://user-images.githubusercontent.com/49102376/149984633-ce216326-2648-4b2b-adc1-a5e9cccf6f11.png">

Original file:
<img width="899" alt="Schermata 2022-01-18 alle 18 00 34" src="https://user-images.githubusercontent.com/49102376/149984652-48c9cabf-d1be-454b-a7af-5ba01f6bba3c.png">

Setting `useSystemFonts` to `true` does not solve this. 

Do you have any other idea?
I guess missing fonts should be installed somewhere: but where (and how) does the conversion take place?

**Comment by dichovsky** [comment]
Hi Elisa,
At this moment this is the best that this package can do. 
To investigate this issue deeper I need more details about your environment.

**Comment by elisaliv** [comment]
Hi Igor,
in the end, I just need to install the missing fonts on my machine (Linux environment). Then it works as expected by setting `useSystemFonts` to `true`.

This way, however, some other PDFs with embedded font information are not correctly converted. 
A possible improvement to the library could be to use the embedded PDF font if present, or otherwise look for it in the system fonts -- no idea if this can be done, though. 

Thank you again!
